name: Run Jest Tests

on:
  push:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # or your project's Node version

      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      - name: Run Jest tests
        run: npm test
        working-directory: ./backend
